import type { Metadata } from "next";
import { LegalPageShell, LegalSection } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms that govern using PerfectLove — pricing, delivery, refunds, and how we handle AI-generated readings.",
};

export default function TermsPage() {
  return (
    <LegalPageShell
      eyebrow="Legal"
      title="Terms of Service"
      lastUpdated="August 11, 2026"
    >
      <LegalSection title="1. Acceptance of These Terms">
        <p>
          PerfectLove (&ldquo;PerfectLove,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;) provides personalized
          astrology, tarot, and soulmate readings through perfectlove.site
          (the &ldquo;Service&rdquo;). By taking a quiz, purchasing a reading, or
          otherwise using the Service, you agree to these Terms of Service.
          If you don&apos;t agree with them, please don&apos;t use the
          Service.
        </p>
      </LegalSection>

      <LegalSection title="2. What the Service Is">
        <p>
          You answer a short quiz about yourself. Based on your answers, we
          generate a personalized reading — and for sketch-based readings, a
          portrait — using AI, and deliver it to the email address you
          provide. Some readings are free to preview; the full version
          unlocks with a one-time payment, unless you&apos;re covered by our
          subscription or bundle (see Section 7).
        </p>
      </LegalSection>

      <LegalSection title="3. Entertainment &amp; Self-Reflection Only">
        <p>
          PerfectLove is provided for entertainment and self-reflection
          purposes. Readings are not scientific, medical, psychological,
          legal, or financial advice, and shouldn&apos;t be treated as a
          substitute for guidance from a qualified professional. Please use
          your own judgment, especially for decisions that matter.
        </p>
      </LegalSection>

      <LegalSection title="4. AI-Generated Content">
        <p>
          Reading text and portraits are generated by AI models based on the
          answers you give us. They are creative interpretations, not
          factual claims or depictions of a real, specific person — a
          soulmate sketch, for example, is an artistic rendering shaped by
          your quiz answers, not a photograph or prediction of an actual
          individual.
        </p>
      </LegalSection>

      <LegalSection title="5. Eligibility">
        <p>
          You must be at least 18 years old, or the age of legal majority
          where you live, to purchase or use PerfectLove.
        </p>
      </LegalSection>

      <LegalSection title="6. Your Account">
        <p>
          Signing in uses a passwordless magic link sent to your email — we
          don&apos;t store a password. Keep access to your email secure,
          since anyone with access to it can sign in to your account and see
          your reading history.
        </p>
      </LegalSection>

      <LegalSection title="7. Pricing &amp; Payment">
        <ul>
          <li>
            Individual readings are one-time purchases, typically priced
            between $1.99 and $6.99 depending on the reading.
          </li>
          <li>
            The Complete Reading Collection unlocks every reading type for a
            one-time $24.99 payment.
          </li>
          <li>
            The Tarot &amp; Astrology subscription is $1.99/month for
            unlimited fresh readings in those two categories, and can be
            canceled anytime from your dashboard — it stays active through
            the end of the billing period you&apos;ve already paid for.
          </li>
          <li>
            All prices are in USD. Payments are processed securely by
            Stripe; PerfectLove never sees or stores your full card number.
          </li>
        </ul>
      </LegalSection>

      <LegalSection title="8. Delivery">
        <p>
          Standard readings are delivered by email within 24 hours of
          purchase, usually sooner. Soulmate Sketch also offers optional
          Express delivery (30 minutes) for an additional fee. Delivery
          times are estimates, not guarantees — occasional delays can
          happen.
        </p>
      </LegalSection>

      <LegalSection title="9. Refunds">
        <p>
          Because readings are generated and typically delivered quickly,
          all sales are final by default. That said, we review refund
          requests on a case-by-case basis — if something went wrong with
          your order, email{" "}
          <a href="mailto:support@perfectlove.site">
            support@perfectlove.site
          </a>{" "}
          with your order details and we&apos;ll take a look. A refund isn&apos;t
          guaranteed, but we&apos;ll always respond.
        </p>
      </LegalSection>

      <LegalSection title="10. Access, Archiving &amp; Expiration">
        <p>
          Purchased readings remain viewable in your dashboard for 60 days
          after delivery. After that window, a reading is archived — you can
          restore access to it at any time for a one-time $1.99 archive
          retrieval fee.
        </p>
      </LegalSection>

      <LegalSection title="11. Acceptable Use">
        <ul>
          <li>Don&apos;t scrape, reverse-engineer, or automate access to the Service.</li>
          <li>Don&apos;t resell, redistribute, or publicly republish readings you purchase.</li>
          <li>Don&apos;t use the Service to harass, impersonate, or harm another person.</li>
        </ul>
      </LegalSection>

      <LegalSection title="12. Intellectual Property">
        <p>
          The PerfectLove name, branding, and platform are owned by
          PerfectLove. A reading you purchase is licensed to you for
          personal, non-commercial use.
        </p>
      </LegalSection>

      <LegalSection title="13. Limitation of Liability">
        <p>
          The Service is provided &ldquo;as is,&rdquo; without warranties of any kind.
          To the fullest extent permitted by law, PerfectLove isn&apos;t
          liable for indirect, incidental, or consequential damages arising
          from your use of the Service, including decisions made based on a
          reading.
        </p>
      </LegalSection>

      <LegalSection title="14. Changes to These Terms">
        <p>
          We may update these Terms from time to time. The &ldquo;Last updated&rdquo;
          date at the top of this page reflects the most recent revision.
          Continuing to use the Service after a change means you accept the
          updated Terms.
        </p>
      </LegalSection>

      <LegalSection title="15. Contact">
        <p>
          Questions about these Terms? Email{" "}
          <a href="mailto:support@perfectlove.site">
            support@perfectlove.site
          </a>
          .
        </p>
      </LegalSection>
    </LegalPageShell>
  );
}
